condition

diff --git a/.github/workflows/job_exec_flow.yaml b/.github/workflows/job_exec_flow.yaml
--- a/.github/workflows/job_exec_flow.yaml
+++ b/.github/workflows/job_exec_flow.yaml
@@ -7,17 +7,17 @@ jobs:
         runs-on: ubuntu-latest
         steps:
             - name: First
-              run: echo exit 1
+              run: exit 1
     job2:
         needs: job1 #job 1 must complete
-        if: ${{always()}} # job1 fail it will execute independently use always()
-        runs-on: ubuntu-latest
-        steps:
-            - name: Second job
-              run: echo "Second Job"
-    job3:
-        needs: job2 #job 2 must complete
+        if: ${{always()}} #condition always() if job1 run or fail job2 will execute
         runs-on: ubuntu-latest
         steps:
             - name: Third Job
               run: echo "Third job"
+    job3:
+        needs: job1 #job 1 must 
+        runs-on: ubuntu-latest
+        steps:
+            - name: third
+              run: echo this is third
